### PR TITLE
Added S-75 value, revised B-1B and C-130.

### PR DESCRIPTION
**Pull request by JMaverick16**

### CODE REVIEW

**Comment by NikolaiVChr** [comment]
Rejected

**Comment by JMaverick16** [comment]
Why so?

**Comment by NikolaiVChr** [comment]
I could ask the same.
You didn't explain your changes, just changed some numbers.
Going to push SA-2 later today btw.

**Comment by JMaverick16** [comment]
B-1B RCS reduction was discussed on OPRF server this morning based on more accurate findings, S-75 value had me and Pinto favourable over voice chat while trying it out, C-130 was dictated by the data found and the fact the airframe being smaller than a 707 hence presumably lower value (B-52 has around 100).

**Pull request closed without merging**
